Deployment script and minor improvements

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -60,8 +60,7 @@ deploy () {
     git push origin gh-pages && \
     ok "Brach gh-pages sucessfully deployed\n" 
 
-    echo $?
-    [[ $? -ne 0 ]] && error "Deployment of brach gh-pages failed"
+    [[ $? -ne 0 ]] && warn "Deployment of brach gh-pages not required or failed"
   fi
 
   cd "${SCRIPT_DIR}"
@@ -71,8 +70,7 @@ deploy () {
   git push origin master && \
   ok "Brach master sucessfully deployed\n"
 
-  echo $?
-  [[ $? -ne 0 ]] && error "Deployment of brach master failed"
+  [[ $? -ne 0 ]] && warn "Deployment of brach master not required or failed"
 }
 
 [[ "$#" == "0" ]] && usage && exit 0
